import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../domain/model/note_model.dart';
import '../../domain/repository/notes_repository.dart';
import '../../../auth/presentation/controllers/auth_controller.dart';

class NotesController extends GetxController {
  final NotesRepository _notesRepository = Get.find<NotesRepository>();
  final AuthController _authController = Get.find<AuthController>();

  final RxList<NoteModel> notes = <NoteModel>[].obs;
  final RxBool isLoading = false.obs;

  @override
  void onInit() {
    super.onInit();
    // Dynamically react to user changes
    ever(_authController.rxUser, _onUserChanged, condition: () => true);
    _onUserChanged(_authController.user);
  }

  void _onUserChanged(dynamic user) {
    if (user != null) {
      notes.bindStream(_notesRepository.getNotesStream(user.uid));
    } else {
      notes.clear();
    }
  }

  Future<bool> addNote(String title, String description) async {
    final user = _authController.user;
    if (user == null) {
      _showErrorSnackBar('User session expired. Please sign in again.');
      return false;
    }

    isLoading.value = true;
    try {
      final note = NoteModel(
        id: '', // Will be generated by Firestore
        title: title.trim(),
        description: description.trim(),
        createdAt: DateTime.now(),
        userId: user.uid,
      );
      await _notesRepository.addNote(note);
      return true;
    } catch (e) {
      _showErrorSnackBar('Failed to save note. Please try again.');
      return false;
    } finally {
      isLoading.value = false;
    }
  }

  Future<bool> updateNote(String id, String title, String description) async {
    final user = _authController.user;
    if (user == null) return false;

    isLoading.value = true;
    try {
      final note = NoteModel(
        id: id,
        title: title.trim(),
        description: description.trim(),
        createdAt: DateTime.now(),
        userId: user.uid,
      );
      await _notesRepository.updateNote(note);
      return true;
    } catch (e) {
      _showErrorSnackBar('Failed to update note.');
      return false;
    } finally {
      isLoading.value = false;
    }
  }

  Future<void> deleteNote(String id) async {
    try {
      await _notesRepository.deleteNote(id);
    } catch (e) {
      _showErrorSnackBar('Failed to delete note.');
    }
  }

  void _showErrorSnackBar(String message) {
    Get.snackbar(
      'Error',
      message,
      snackPosition: SnackPosition.BOTTOM,
      backgroundColor: const Color(0xFFC13515), // AppColors.error
      colorText: const Color(0xFFFFFFFF), // AppColors.onError
      margin: const EdgeInsets.all(16.0),
      borderRadius: 8.0,
    );
  }
}
